// Auto-generated by contracts/scripts/generate-relayer-config.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

import type { ChainConfig } from './types.js'

// Chain configurations with deployment addresses
export const CHAIN_CONFIGS: Record<string, ChainConfig> = {
  flowEvm: {
    chainId: 747,
    name: 'Flow EVM',
    rpcUrl: process.env.FLOW_EVM_RPC || 'https://mainnet.evm.nodes.onflow.org',
    policyManagerAddress: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345' as `0x${string}`,
    startBlock: 56881090,
    pollIntervalMs: 15000,
    batchSize: 9000,
    confirmations: 2,
    enabled: true,
  },
  base: {
    chainId: 8453,
    name: 'Base',
    rpcUrl: process.env.BASE_RPC || 'https://mainnet.base.org',
    policyManagerAddress: '0x037A24595E96B10d9FB2c7c2668FE5e7F354c86a' as `0x${string}`,
    startBlock: 42554078,
    pollIntervalMs: 60000,
    batchSize: 5,
    confirmations: 5,
    enabled: true,
  },
  baseSepolia: {
    chainId: 84532,
    name: 'Base Sepolia',
    rpcUrl: process.env.BASE_SEPOLIA_RPC || 'https://sepolia.base.org',
    policyManagerAddress: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345' as `0x${string}`,
    startBlock: 38095092,
    pollIntervalMs: 2000,
    batchSize: 10000,
    confirmations: 2,
    enabled: false,
  }
} as const

// Deployment metadata
export const DEPLOYMENTS = {
  "747": {
    "chainId": 747,
    "chainName": "flowEvm",
    "deployedAt": "2026-02-20T23:04:32Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 56881090,
    "contracts": {
      "policyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0xF1815bd50389c46847f0Bda824eC8da914045D14",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "8453": {
    "chainId": 8453,
    "chainName": "base",
    "deployedAt": "2026-02-24T01:45:03Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 42554078,
    "contracts": {
      "policyManager": "0x037A24595E96B10d9FB2c7c2668FE5e7F354c86a"
    },
    "addresses": {
      "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "84532": {
    "chainId": 84532,
    "chainName": "baseSepolia",
    "deployedAt": "2026-02-24T18:41:12Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 38095092,
    "contracts": {
      "policyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  }
} as const

// Get enabled chains, filtered by ENABLED_CHAINS env var if set.
// Usage: ENABLED_CHAINS=baseSepolia (staging) or ENABLED_CHAINS=flowEvm,base (production)
// If unset, returns all chains with enabled: true in their config.
export function getEnabledChainConfigs(): ChainConfig[] {
  const override = process.env.ENABLED_CHAINS?.split(',').map(s => s.trim()).filter(Boolean)
  if (override?.length) {
    return Object.entries(CHAIN_CONFIGS)
      .filter(([key]) => override.includes(key))
      .map(([, c]) => c)
  }
  return Object.values(CHAIN_CONFIGS).filter(c => c.enabled)
}

// Get chain config by ID
export function getChainConfigById(chainId: number): ChainConfig | undefined {
  return Object.values(CHAIN_CONFIGS).find(c => c.chainId === chainId)
}
