// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/*
                  ╔══════════════════════════════╗
                  ║   AutoPay Privacy Router     ║
                  ╚══════════════════════════════╝

    Hides the merchant ↔ customer relationship on-chain using
    two composable third-party privacy primitives:

    Layer 1 — Stealth Addresses (ERC-5564 / Umbra)
      Merchant registers a stealth meta-address (spending + viewing keys).
      Each subscription generates a unique one-time stealth address so
      on-chain observers cannot link payments to the merchant's real wallet.

    Layer 2 — RAILGUN Shielded Payments (optional)
      Customers can shield USDC into RAILGUN before subscribing,
      hiding the payer side as well.  The PrivacyRouter acts as a
      Relay Adapt target for RAILGUN cross-contract calls.

    Together these break the on-chain graph:
      payer (shielded) → stealth address (unlinkable to merchant)
*/

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

// ── Third-party interfaces ──────────────────────────────────────────
import {IStealthAddressRegistry} from "../interfaces/IStealthAddressRegistry.sol";

// ── Errors ──────────────────────────────────────────────────────────
error MerchantNotRegistered();
error InvalidStealthAddress();
error AnnouncementFailed();
error PolicyManagerCallFailed();

/**
 * @title PrivacyRouter
 * @author AutoPay Protocol
 * @notice Privacy wrapper around PolicyManager that routes subscription
 *         payments through stealth addresses so that the merchant ↔ customer
 *         link is invisible on-chain.
 *
 * @dev Architecture:
 *
 *   ┌──────────┐   createPrivatePolicy()   ┌────────────────┐
 *   │  Payer   │ ────────────────────────→  │ PrivacyRouter  │
 *   └──────────┘                            └───────┬────────┘
 *                                                   │
 *                          ┌────────────────────────┤
 *                          ▼                        ▼
 *                 ┌─────────────────┐     ┌──────────────────┐
 *                 │ PolicyManager   │     │ ERC-5564 Announce │
 *                 │ (policy.merchant│     │ (ephemeral pubkey │
 *                 │  = stealth addr)│     │  + view tag)      │
 *                 └─────────────────┘     └──────────────────┘
 *
 *   The merchant's relayer scans Announcements with their viewing key
 *   to discover which stealth addresses belong to them, then derives
 *   the spending key to withdraw funds.
 */
contract PrivacyRouter is ReentrancyGuard, Ownable {
    using SafeERC20 for IERC20;

    // ── Constants ───────────────────────────────────────────────────
    uint256 private constant GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798;
    uint256 private constant GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8;
    // secp256k1 curve order
    uint256 private constant N  = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141;

    // ── Immutables ──────────────────────────────────────────────────
    IERC20 public immutable USDC;
    address public immutable policyManager;

    // ── State ───────────────────────────────────────────────────────

    /// @notice ERC-5564-compatible stealth address registry (e.g. Umbra's ERC-6538 registry)
    IStealthAddressRegistry public stealthRegistry;

    /// @notice Maps stealth address → true if generated by this router
    mapping(address => bool) public isStealthAddress;

    /// @notice Maps stealth address → merchant who can claim it
    /// @dev Only stored in the router; the PolicyManager just sees an opaque address.
    ///      The merchant discovers stealth addresses off-chain via Announcement scanning.
    mapping(address => address) private stealthToMerchant;

    // ── Events ──────────────────────────────────────────────────────

    /// @notice ERC-5564-compatible announcement so merchants can scan for their payments
    /// @param schemeId      1 = secp256k1 (standard)
    /// @param stealthAddress The generated one-time address
    /// @param caller        Who sent the transaction (may be RAILGUN relay)
    /// @param ephemeralPubKeyX  X-coordinate of ephemeral public key R
    /// @param ephemeralPubKeyY  Y-coordinate of ephemeral public key R
    /// @param viewTag       First byte of shared secret — fast scanning filter
    /// @param metadata      Arbitrary metadata (policyId, etc.)
    event Announcement(
        uint256 indexed schemeId,
        address indexed stealthAddress,
        address indexed caller,
        uint256 ephemeralPubKeyX,
        uint256 ephemeralPubKeyY,
        bytes1 viewTag,
        bytes metadata
    );

    /// @notice Emitted when a private policy is created
    event PrivatePolicyCreated(
        bytes32 indexed policyId,
        address indexed stealthMerchant,
        uint128 chargeAmount,
        uint32 interval
    );

    // ── Constructor ─────────────────────────────────────────────────

    constructor(
        address _usdc,
        address _policyManager,
        address _stealthRegistry
    ) Ownable(msg.sender) {
        USDC = IERC20(_usdc);
        policyManager = _policyManager;
        stealthRegistry = IStealthAddressRegistry(_stealthRegistry);
    }

    // ── Core: Private Subscription Creation ─────────────────────────

    /**
     * @notice Create a subscription policy where the merchant address is a
     *         one-time stealth address, unlinkable to the merchant's real wallet.
     *
     * @dev Flow:
     *   1. Look up merchant's stealth meta-address from the registry
     *   2. Generate a stealth address from the ephemeral key pair provided
     *   3. Create the policy on PolicyManager with stealthAddr as the merchant
     *   4. Emit an ERC-5564 Announcement so the merchant can discover the payment
     *
     * @param merchant           The real merchant address (used to look up stealth keys)
     * @param chargeAmount       USDC amount per charge
     * @param interval           Seconds between charges
     * @param spendingCap        Max total lifetime spend (0 = unlimited)
     * @param metadataUrl        Off-chain metadata URL
     * @param stealthAddress     The pre-computed stealth address for the merchant
     * @param ephemeralPubKeyX   X-coordinate of ephemeral public key R (generated off-chain)
     * @param ephemeralPubKeyY   Y-coordinate of ephemeral public key R (generated off-chain)
     * @param viewTag            First byte of the shared secret for fast scanning
     * @return policyId          The policy ID from PolicyManager
     */
    function createPrivatePolicy(
        address merchant,
        uint128 chargeAmount,
        uint32 interval,
        uint128 spendingCap,
        string calldata metadataUrl,
        address stealthAddress,
        uint256 ephemeralPubKeyX,
        uint256 ephemeralPubKeyY,
        bytes1 viewTag
    ) external nonReentrant returns (bytes32 policyId) {
        // 1. Verify merchant has registered stealth keys
        (uint256 spkX, uint256 spkY,,) = stealthRegistry.stealthKeys(merchant);
        if (spkX == 0 && spkY == 0) revert MerchantNotRegistered();

        // 2. Validate the stealth address is non-zero
        if (stealthAddress == address(0)) revert InvalidStealthAddress();

        // 3. Record the stealth address mapping
        isStealthAddress[stealthAddress] = true;
        stealthToMerchant[stealthAddress] = merchant;

        // 4. Transfer USDC from payer and approve PolicyManager
        USDC.safeTransferFrom(msg.sender, address(this), chargeAmount);
        USDC.approve(policyManager, chargeAmount);

        // 5. Create the policy with the stealth address as merchant
        //    The PolicyManager sees an opaque address — no link to real merchant
        (bool success, bytes memory result) = policyManager.call(
            abi.encodeWithSignature(
                "createPolicy(address,uint128,uint32,uint128,string)",
                stealthAddress,
                chargeAmount,
                interval,
                spendingCap,
                metadataUrl
            )
        );
        if (!success) revert PolicyManagerCallFailed();
        policyId = abi.decode(result, (bytes32));

        // 6. Emit ERC-5564 Announcement for the merchant's scanner
        emit Announcement(
            1,                    // schemeId = secp256k1
            stealthAddress,
            msg.sender,
            ephemeralPubKeyX,
            ephemeralPubKeyY,
            viewTag,
            abi.encode(policyId)  // metadata: the policyId for correlation
        );

        emit PrivatePolicyCreated(policyId, stealthAddress, chargeAmount, interval);
    }

    // ── Admin ───────────────────────────────────────────────────────

    /**
     * @notice Update the stealth registry address (e.g. migrate to a new Umbra deployment)
     */
    function setStealthRegistry(address _stealthRegistry) external onlyOwner {
        stealthRegistry = IStealthAddressRegistry(_stealthRegistry);
    }

    /**
     * @notice Rescue tokens accidentally sent to this contract
     */
    function rescueTokens(address token, address to, uint256 amount) external onlyOwner {
        IERC20(token).safeTransfer(to, amount);
    }

    // ── View helpers ────────────────────────────────────────────────

    /**
     * @notice Check if a merchant has registered stealth keys
     */
    function isMerchantPrivate(address merchant) external view returns (bool) {
        (uint256 spkX, uint256 spkY,,) = stealthRegistry.stealthKeys(merchant);
        return (spkX != 0 || spkY != 0);
    }
}
