// Auto-generated by contracts/scripts/generate-agent-sdk-chains.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

export type ChainKey = 'flowEvm' | 'base' | 'polkadotHub' | 'tempo' | 'arcTestnet' | 'baseSepolia'

export interface NativeCurrency {
  name: string
  symbol: string
  decimals: number
}

export interface AgentChainConfig {
  name: string
  chainId: number
  rpcUrl: string
  policyManager: `0x${string}`
  usdc: `0x${string}`
  explorer: string
  nativeCurrency: NativeCurrency
}

export const chains: Record<ChainKey, AgentChainConfig> = {
  flowEvm: {
    name: 'Flow EVM',
    chainId: 747,
    rpcUrl: 'https://mainnet.evm.nodes.onflow.org',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    usdc: '0xF1815bd50389c46847f0Bda824eC8da914045D14',
    explorer: 'https://evm.flowscan.io',
    nativeCurrency: { name: 'FLOW', symbol: 'FLOW', decimals: 18 },
  },
  base: {
    name: 'Base',
    chainId: 8453,
    rpcUrl: 'https://mainnet.base.org',
    policyManager: '0x037A24595E96B10d9FB2c7c2668FE5e7F354c86a',
    usdc: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    explorer: 'https://basescan.org',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  polkadotHub: {
    name: 'Polkadot Hub',
    chainId: 420420419,
    rpcUrl: 'https://eth-rpc.polkadot.io/',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    usdc: '0x0000053900000000000000000000000001200000',
    explorer: 'https://blockscout.polkadot.io',
    nativeCurrency: { name: 'DOT', symbol: 'DOT', decimals: 18 },
  },
  tempo: {
    name: 'Tempo',
    chainId: 4217,
    rpcUrl: 'https://rpc.tempo.xyz',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    usdc: '0x20c000000000000000000000b9537d11c60e8b50',
    explorer: 'https://explore.tempo.xyz',
    nativeCurrency: { name: 'USD', symbol: 'USD', decimals: 6 },
  },
  arcTestnet: {
    name: 'Arc Testnet',
    chainId: 5042002,
    rpcUrl: 'https://rpc.testnet.arc.network',
    policyManager: '0xe3463a10Cb69D9705A38cECac3cBC58AD76f5De1',
    usdc: '0x3600000000000000000000000000000000000000',
    explorer: 'https://testnet.arcscan.app',
    nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 6 },
  },
  baseSepolia: {
    name: 'Base Sepolia',
    chainId: 84532,
    rpcUrl: 'https://sepolia.base.org',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    usdc: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    explorer: 'https://sepolia.basescan.org',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  }
}
