// Auto-generated by contracts/scripts/generate-agent-sdk-chains.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

export type ChainKey = 'flowEvm' | 'base' | 'baseSepolia'

export interface NativeCurrency {
  name: string
  symbol: string
  decimals: number
}

export interface AgentChainConfig {
  name: string
  chainId: number
  rpcUrl: string
  policyManager: `0x${string}`
  usdc: `0x${string}`
  explorer: string
  nativeCurrency: NativeCurrency
}

export const chains: Record<ChainKey, AgentChainConfig> = {
  flowEvm: {
    name: 'Flow EVM',
    chainId: 747,
    rpcUrl: 'https://mainnet.evm.nodes.onflow.org',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    usdc: '0xF1815bd50389c46847f0Bda824eC8da914045D14',
    explorer: 'https://evm.flowscan.io',
    nativeCurrency: { name: 'FLOW', symbol: 'FLOW', decimals: 18 },
  },
  base: {
    name: 'Base',
    chainId: 8453,
    rpcUrl: 'https://mainnet.base.org',
    policyManager: '0x037A24595E96B10d9FB2c7c2668FE5e7F354c86a',
    usdc: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    explorer: 'https://basescan.org',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  baseSepolia: {
    name: 'Base Sepolia',
    chainId: 84532,
    rpcUrl: 'https://sepolia.base.org',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    usdc: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    explorer: 'https://sepolia.basescan.org',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  }
}
