// Auto-generated by contracts/scripts/generate-raffle-config.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

export const CHAINS = {
  flowEvm: {
    chainId: 747,
    rpcUrl: 'https://mainnet.evm.nodes.onflow.org',
    usdc: '0xF1815bd50389c46847f0Bda824eC8da914045D14',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    explorer: 'https://evm.flowscan.io',
  },
  base: {
    chainId: 8453,
    rpcUrl: 'https://mainnet.base.org',
    usdc: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    policyManager: '0x037A24595E96B10d9FB2c7c2668FE5e7F354c86a',
    explorer: 'https://basescan.org',
  },
  baseSepolia: {
    chainId: 84532,
    rpcUrl: 'https://sepolia.base.org',
    usdc: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    policyManager: '0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345',
    explorer: 'https://sepolia.basescan.org',
  }
}
