// Auto-generated by contracts/scripts/generate-frontend-chains.js
// Do not edit manually - run 'make sync' in contracts/ to regenerate

import { defineChain, type Chain } from 'viem'
import { DEPLOYMENTS } from './deployments'

export const flowEvmMainnet = defineChain({
  id: 747,
  name: 'Flow EVM',
  nativeCurrency: { decimals: 18, name: 'FLOW', symbol: 'FLOW' },
  rpcUrls: { default: { http: [import.meta.env.VITE_FLOW_EVM_RPC || 'https://mainnet.evm.nodes.onflow.org'] } },
  blockExplorers: { default: { name: 'Flowscan', url: 'https://evm.flowscan.io' } },
})

export const baseMainnet = defineChain({
  id: 8453,
  name: 'Base',
  nativeCurrency: { decimals: 18, name: 'Ether', symbol: 'ETH' },
  rpcUrls: { default: { http: [import.meta.env.VITE_BASE_RPC || 'https://mainnet.base.org'] } },
  blockExplorers: { default: { name: 'BaseScan', url: 'https://basescan.org' } },
})

export const baseSepoliaMainnet = defineChain({
  id: 84532,
  name: 'Base Sepolia',
  nativeCurrency: { decimals: 18, name: 'Ether', symbol: 'ETH' },
  rpcUrls: { default: { http: [import.meta.env.VITE_BASE_SEPOLIA_RPC || 'https://sepolia.base.org'] } },
  blockExplorers: { default: { name: 'BaseScan Sepolia', url: 'https://sepolia.basescan.org' } },
})

export interface ChainConfig {
  key: string
  chain: Chain
  name: string
  shortName: string
  usdc: `0x${string}`
  policyManager?: `0x${string}`
  deployBlock?: number
  explorer: string
  supportsLifi: boolean
  enabled: boolean
}

export const CHAIN_CONFIGS = {
  flowEvm: {
    key: 'flowEvm',
    chain: flowEvmMainnet,
    name: 'Flow EVM',
    shortName: 'Flow',
    usdc: '0xF1815bd50389c46847f0Bda824eC8da914045D14',
    policyManager: DEPLOYMENTS[747]?.contracts.policyManager as `0x${string}` | undefined,
    deployBlock: DEPLOYMENTS[747]?.deployBlock,
    explorer: 'https://evm.flowscan.io',
    supportsLifi: true,
    enabled: true,
  },
  base: {
    key: 'base',
    chain: baseMainnet,
    name: 'Base',
    shortName: 'Base',
    usdc: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    policyManager: DEPLOYMENTS[8453]?.contracts.policyManager as `0x${string}` | undefined,
    deployBlock: DEPLOYMENTS[8453]?.deployBlock,
    explorer: 'https://basescan.org',
    supportsLifi: true,
    enabled: true,
  },
  baseSepolia: {
    key: 'baseSepolia',
    chain: baseSepoliaMainnet,
    name: 'Base Sepolia',
    shortName: 'Base Sepolia',
    usdc: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
    policyManager: DEPLOYMENTS[84532]?.contracts.policyManager as `0x${string}` | undefined,
    deployBlock: DEPLOYMENTS[84532]?.deployBlock,
    explorer: 'https://sepolia.basescan.org',
    supportsLifi: false,
    enabled: false,
  }
} satisfies Record<string, ChainConfig>

export type ChainKey = keyof typeof CHAIN_CONFIGS
export const ENABLED_CHAINS = Object.values(CHAIN_CONFIGS).filter(c => c.enabled)
export const DEFAULT_CHAIN = (import.meta.env.VITE_DEFAULT_CHAIN || 'flowEvm') as ChainKey
