// Auto-generated by scripts/generate-contracts-ts.js
// Do not edit manually - run 'make sync' to regenerate

import PolicyManagerAbi from './abis/PolicyManager.json';

export { PolicyManagerAbi };

// Chain configurations
export const CHAINS = {
  "flowEvm": {
    "id": 747,
    "name": "Flow EVM",
    "rpcUrl": "https://mainnet.evm.nodes.onflow.org",
    "usdc": "0xF1815bd50389c46847f0Bda824eC8da914045D14",
    "blockExplorer": "https://evm.flowscan.io"
  }
} as const;

// Deployment addresses by chain ID
export const DEPLOYMENTS: Record<number, Deployment> = {
  "747": {
    "chainId": 747,
    "chainName": "flowEvm",
    "deployedAt": "2026-02-20T23:04:32Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 56881090,
    "contracts": {
      "policyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0xF1815bd50389c46847f0Bda824eC8da914045D14",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "5042002": {
    "chainId": 5042002,
    "chainName": "arcTestnet",
    "deployedAt": "2026-02-12T02:51:00Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 26573469,
    "contracts": {
      "arcPolicyManager": "0xe3463a10Cb69D9705A38cECac3cBC58AD76f5De1"
    },
    "addresses": {
      "usdc": "0x3600000000000000000000000000000000000000",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  }
};

// Types
export interface Deployment {
  chainId: number;
  chainName: string;
  deployedAt: string;
  deployer: string;
  deployBlock?: number;
  contracts: {
    policyManager?: string;
  };
  addresses: {
    usdc: string;
    feeRecipient: string;
  };
}

// Helpers
export function getContractAddress(
  chainId: number,
  contract: 'policyManager'
): `0x${string}` {
  const deployment = DEPLOYMENTS[chainId];
  if (!deployment) {
    throw new Error(`No deployment found for chain ${chainId}`);
  }
  const address = deployment.contracts[contract];
  if (!address) {
    throw new Error(`Contract ${contract} not deployed on chain ${chainId}`);
  }
  return address as `0x${string}`;
}

export function getChainConfig(chainId: number) {
  const chain = Object.values(CHAINS).find(c => c.id === chainId);
  if (!chain) {
    throw new Error(`Unknown chain ${chainId}`);
  }
  return chain;
}
