// Auto-generated by scripts/generate-contracts-ts.js
// Do not edit manually - run 'make sync' to regenerate

import ArcPolicyManagerAbi from './abis/ArcPolicyManager.json';
// import PolicyManagerAbi from './abis/PolicyManager.json';

export { ArcPolicyManagerAbi };

// Chain configurations
export const CHAINS = {
  "arcTestnet": {
    "id": 5042002,
    "name": "Arc Testnet",
    "rpcUrl": "https://rpc.testnet.arc.network",
    "usdc": "0x3600000000000000000000000000000000000000",
    "blockExplorer": "https://testnet.arcscan.app"
  }
} as const;

// Deployment addresses by chain ID
export const DEPLOYMENTS: Record<number, Deployment> = {
  "5042002": {
    "chainId": 5042002,
    "chainName": "arcTestnet",
    "deployedAt": "2026-02-04T01:40:36Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "contracts": {
      "arcPolicyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0x3600000000000000000000000000000000000000",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  }
};

// Types
export interface Deployment {
  chainId: number;
  chainName: string;
  deployedAt: string;
  deployer: string;
  contracts: {
    arcPolicyManager?: string;
    policyManager?: string;
  };
  addresses: {
    usdc: string;
    feeRecipient: string;
  };
}

// Helpers
export function getContractAddress(
  chainId: number,
  contract: 'arcPolicyManager' | 'policyManager'
): `0x${string}` {
  const deployment = DEPLOYMENTS[chainId];
  if (!deployment) {
    throw new Error(`No deployment found for chain ${chainId}`);
  }
  const address = deployment.contracts[contract];
  if (!address) {
    throw new Error(`Contract ${contract} not deployed on chain ${chainId}`);
  }
  return address as `0x${string}`;
}

export function getChainConfig(chainId: number) {
  const chain = Object.values(CHAINS).find(c => c.id === chainId);
  if (!chain) {
    throw new Error(`Unknown chain ${chainId}`);
  }
  return chain;
}
