// Auto-generated by scripts/generate-contracts-ts.js
// Do not edit manually - run 'make sync' to regenerate

import PolicyManagerAbi from './abis/PolicyManager.json';

export { PolicyManagerAbi };

// Chain configurations
export const CHAINS = {
  "flowEvm": {
    "id": 747,
    "name": "Flow EVM",
    "rpcUrl": "https://mainnet.evm.nodes.onflow.org",
    "usdc": "0xF1815bd50389c46847f0Bda824eC8da914045D14",
    "blockExplorer": "https://evm.flowscan.io"
  },
  "base": {
    "id": 8453,
    "name": "Base",
    "rpcUrl": "https://mainnet.base.org",
    "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "blockExplorer": "https://basescan.org"
  },
  "polkadotHub": {
    "id": 420420419,
    "name": "Polkadot Hub",
    "rpcUrl": "https://eth-rpc.polkadot.io/",
    "usdc": "0x0000053900000000000000000000000001200000",
    "blockExplorer": "https://blockscout.polkadot.io"
  },
  "baseSepolia": {
    "id": 84532,
    "name": "Base Sepolia",
    "rpcUrl": "https://sepolia.base.org",
    "usdc": "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
    "blockExplorer": "https://sepolia.basescan.org"
  }
} as const;

// Deployment addresses by chain ID
export const DEPLOYMENTS: Record<number, Deployment> = {
  "747": {
    "chainId": 747,
    "chainName": "flowEvm",
    "deployedAt": "2026-02-20T23:04:32Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 56881090,
    "contracts": {
      "policyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0xF1815bd50389c46847f0Bda824eC8da914045D14",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "8453": {
    "chainId": 8453,
    "chainName": "base",
    "deployedAt": "2026-02-24T01:45:03Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 42554078,
    "contracts": {
      "policyManager": "0x037A24595E96B10d9FB2c7c2668FE5e7F354c86a"
    },
    "addresses": {
      "usdc": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "84532": {
    "chainId": 84532,
    "chainName": "baseSepolia",
    "deployedAt": "2026-02-24T18:41:12Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 38095092,
    "contracts": {
      "policyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  },
  "420420419": {
    "chainId": 420420419,
    "chainName": "polkadotHub",
    "deployedAt": "2026-03-15T00:58:57Z",
    "deployer": "0x7E31DF5336c97BE4Fe34B4D05CbBaae354d383F9",
    "deployBlock": 13412400,
    "contracts": {
      "policyManager": "0x5EDAF928C94A249C5Ce1eaBaD0fE799CD294f345"
    },
    "addresses": {
      "usdc": "0x0000053900000000000000000000000001200000",
      "feeRecipient": "0x2B8b9182c1c3A9bEf4a60951D9B7F49420D12B9B"
    }
  }
};

// Types
export interface Deployment {
  chainId: number;
  chainName: string;
  deployedAt: string;
  deployer: string;
  deployBlock?: number;
  contracts: {
    policyManager?: string;
  };
  addresses: {
    usdc: string;
    feeRecipient: string;
  };
}

// Helpers
export function getContractAddress(
  chainId: number,
  contract: 'policyManager'
): `0x${string}` {
  const deployment = DEPLOYMENTS[chainId];
  if (!deployment) {
    throw new Error(`No deployment found for chain ${chainId}`);
  }
  const address = deployment.contracts[contract];
  if (!address) {
    throw new Error(`Contract ${contract} not deployed on chain ${chainId}`);
  }
  return address as `0x${string}`;
}

export function getChainConfig(chainId: number) {
  const chain = Object.values(CHAINS).find(c => c.id === chainId);
  if (!chain) {
    throw new Error(`Unknown chain ${chainId}`);
  }
  return chain;
}
